'''
Created on Apr 2, 2019

@author: sojin
'''
# Define screen size
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 800
BALL_MOVE_SPEED = 2

# Game Speed
GAME_SPEED_EASY = 150
GAME_SPEED_MED = 170
GAME_SPEED_HARD = 200
GAME_SPEED_IMPOSSIBLE = 250

# Number of balls
BALL_LIMIT_EASY = 5
BALL_LIMIT_MED = 6
BALL_LIMIT_HARD = 8
BALL_LIMIT_IMPOSSIBLE = 10